config/routes.rb
Pdftest::Application.routes.draw do
  get 'welcome/index'

  resources :profiles

  root 'welcome#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	def new 
	end 

	def create 
		#@profile = Profile.new(params[:profile])
		#profile_data = []
		#profile_data << params[:profile][:first_name]

=begin
		respond_to do |format|
			format.pdf { send_file ProfileSummary.new(params[:profile]).export, type: 'application/pdf' }
		end 
=end

		send_file ProfileSummary.new(params[:profile]).export, type: 'application/pdf'

		# render json: params[:profile].inspect
		# render json: profile_data.inspect
		# fill pdf form
	end 

	def edit
	end 

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pdftest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/profiles/new.html.erb
<h1>Profile Information</h1>
<%= form_for :profile, url: profiles_path do |p| %>

	<p>
	<label><%= p.label :first_name %></label>
	<%= p.text_field :first_name %>
	</p>

	<p>
	<label><%= p.label :last_name %></label>
	<%=p.text_field :last_name %>
	</p>

	<p>
	<label><%= p.label :dob %></label>
	<%= p.text_field :dob %>
	</p>

	<p>
	<%= p.submit %>
	</p>

<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to the PDF Test Application</h1>

Hope you love it here...

<p><%= link_to 'Signup', new_profile_path %></p>